const toolsData = {
    "system_tools": [
        {
            "name": "SuperF4",
            "description": "Kill programs instantly with Ctrl+Alt+F4.",
            "version": "1.4",
            "size": "138 KB",
            "platform": "Windows",
            "status": "Downloadable",
            "status_color": "#b39dff",
            "download_url": "https://github.com/stefansundin/superf4/releases/download/v1.4/SuperF4-1.4.exe",
            "download_text": "Download the app",
            "icon": "https://stefansundin.github.io/superf4/img/icon128.png",
            "details": "SuperF4 kills the foreground program when you press Ctrl+Alt+F4. This is different from when you press Alt+F4. When you press Alt+F4, the program can refuse to quit. Windows only asks the program to quit, and lets it decide for itself what to do."
        },
        {
            "name": "Bulk Crap Uninstaller",
            "description": "Remove large amounts of applications with minimal to no user input.",
            "version": "5.9",
            "size": "7.8 MB",
            "platform": "Windows",
            "status": "Downloadable",
            "status_color": "#b39dff",
            "download_url": "https://github.com/Klocman/Bulk-Crap-Uninstaller/releases/download/v5.9/BCUninstaller_5.9.0_setup.exe",
            "download_text": "Download the app",
            "icon": "https://img.utdstc.com/icon/c8a/247/c8a2479faaa76ad5a87b76e07881570260d5647e36dcfe887a720234208e13d4:200",
            "details": "Bulk Crap Uninstaller (in short BCUninstaller or BCU) is a free (as in speech and beer) bulk program uninstaller with advanced automation. It excels at removing large amounts of applications with minimal to no user input, while requiring next to no technical knowledge."
        },
        {
            "name": "PolicyPlus",
            "description": "Local Group Policy Editor plus more, for all Windows editions.",
            "version": "October 2025 Snapshot",
            "size": "364 KB",
            "platform": "Windows",
            "status": "Downloadable",
            "status_color": "#b39dff",
            "download_url": "https://github.com/Fleex255/PolicyPlus/releases/download/October2025/PolicyPlus.exe",
            "download_text": "Download the app",
            "details": "Policy Plus is a local Group Policy Editor for all versions of Windows. It allows you to view and edit policy settings on computers that don't have Group Policy Editor installed, or to manage policy settings remotely."
        },
        {
            "name": "Edge Uninstall",
            "description": "A script to uninstall Microsoft Edge completely from your system.",
            "version": "1.0",
            "size": "1.2 KB",
            "platform": "Windows",
            "status": "Downloadable",
            "status_color": "#b39dff",
            "download_url": "uninstall_edge.bat",
            "download_text": "Download Edge Uninstaller",
            "details": "Batch file that runs a PowerShell script to completely remove Microsoft Edge from Windows. Run as Administrator for best results."
        },
      {
            "name": "EarTrumpet",
            "description": "Advanced volume control for Windows.",
            "version": "1.0",
            "size": "7.5 MB",
            "platform": "Windows",
            "status": "Downloadable",
            "status_color": "#b39dff",
            "download_url": "https://apps.microsoft.com/store/detail/eartrumpet/9NBLGGH516XP?mode=full&cid=eartrumpet.landing",
            "download_text": "Download the app from Microsoft Store",
            "icon": "https://static0.makeuseofimages.com/wordpress/wp-content/uploads/2025/12/eartrumpet-app-logo.png?q=70&fit=contain&w=420&dpr=1",
            "details": "EarTrumpet is a powerful volume control app for Windows that allows you to manage the volume of individual applications with ease. It integrates seamlessly with the Windows taskbar and provides a more intuitive way to control audio levels."
        },
        {
            "name": "AltSnap",
            "description": "Enhance Windows dragging with additional features.",
            "version": "1.67",
            "size": "184 KB",
            "platform": "Windows",
            "status": "Downloadable",
            "status_color": "#b39dff",
            "download_url": "https://github.com/RamonUnch/AltSnap/releases/download/1.67/AltSnap1.67-inst.exe",
            "download_text": "Download the app",
            "icon": "https://mloads.com/uploads/posts/2024-11/altsnap.webp",
            "details": "AltSnap is a lightweight Windows utility that enhances window management by allowing you to move and resize windows using the Alt key, similar to Linux/Unix desktop environments."
        },
       {
            "name": "HWiNFO",
            "description": "System information and hardware monitoring tool.",
            "version": "8.40",
            "size": "18 KB",
            "platform": "Windows",
            "status": "Downloadable",
            "status_color": "#b39dff",
            "download_url": "https://www.hwinfo.com/files/hwi64_840.exe",
            "download_text": "Download the app",
            "icon": "https://www.hwinfo.com/wp-content/themes/hwinfo/img/logo-sm.png",
            "details": "HWiNFO is a system information and hardware monitoring tool that provides detailed information about your computer's hardware components."
        },
        {
            "name": "Monitorian",
            "description": "A Windows desktop tool to adjust the brightness of multiple monitors with ease.",
            "version": "4.13.0",
            "size": "629 KB",
            "platform": "Windows",
            "status": "Downloadable",
            "status_color": "#b39dff",
            "download_url": "https://github.com/emoacht/Monitorian/releases/download/4.13.0-Installer/MonitorianInstaller4130.zip",
            "download_text": "Download the app",
            "icon": "https://store-images.s-microsoft.com/image/apps.34982.14453285281266867.f7b19530-4829-4646-9985-b7e1e716c416.2a3d0398-0d33-46a3-b739-47b31af65e59?h=210",
            "details": "Monitorian is a Windows desktop tool to adjust the brightness of multiple monitors with ease."
        },
      {
            "name": "MAS",
            "description": "Windows and Office Activation Script.",
            "version": "3.9",
            "platform": "Windows",
            "status": "Script Available",
            "status_color": "#b39dff",
            "download_url": "https://massgrave.dev",
            "download_text": "Visit MAS",
            "icon": "https://massgrave.dev/img/logo.png",
            "details": "MAS (Microsoft Activation Script) is a powerful and user-friendly script designed to help users activate Windows and Microsoft Office products easily and efficiently."
        },
        {
            "name": "VCRedist",
            "description": "AIO Repack for latest Microsoft Visual C++ Redistributable Runtimes, without the original setup bloat payload.",
            "version": "0.103.0",
            "platform": "Windows",
            "status": "Downloadable",
            "status_color": "#b39dff",
            "download_url": "https://github.com/abbodi1406/vcredist/releases/download/v0.103.0/VisualCppRedist_AIO_x86_x64.exe",
            "download_text": "Download the repack",
            "icon": "https://vcredist.com/img/vcredist.png",
            "details": "VCRedist is an all-in-one repack for the latest Microsoft Visual C++ Redistributable Runtimes, designed to provide a streamlined installation experience without the bloat of original setup payloads."
        },
    ]
};